export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";

export const PROFILE_LOADING = "PROFILE_LOADING";

export const USER_PROFILE_NOT_FOUND = "USER_PROFILE_NOT_FOUND";

export const CLEAR_USER_PROFILE = "CLEAR_USER_PROFILE";

export const GET_USER_PROFILES_REQUEST = "GET_USER_PROFILES_REQUEST";
export const GET_USER_PROFILES_SUCCESS = "GET_USER_PROFILES_SUCCESS";

export const ADD_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS";
export const ADD_EDUCATION_SUCCESS = "ADD_EDUCATION_SUCCESS";

export const GET_PROFILE_BY_HANDLE_SUCCESS = "GET_PROFILE_BY_HANDLE_SUCCESS";
export const GET_ALL_PROFILES_SUCCESS = "GET_ALL_PROFILES_SUCCESS";
