export const POST_LOADING_REQUEST = "POST_LOADING_REQUEST";
export const CLEAR_POST_ERRORS = "CLEAR_POST_ERRORS";

export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
